### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by mama110** [andy-yun/pytorch-0.4-yolov3#33]
I trained VOC2007 by 105 epochs, then an error occured, i don't know why, can anyone help me? Thanks.
the error as follows:

Traceback (most recent call last):
  File "train.py", line 372, in <module>
    main()
  File "train.py", line 154, in main
    nsamples = train(epoch)
  File "train.py", line 216, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "f:\Anaconda3\envs\spurs\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "f:\Anaconda3\envs\spurs\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "f:\Anaconda3\envs\spurs\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "f:\Anaconda3\envs\spurs\lib\site-packages\torch\utils\data\dataloader.py", line 187, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "f:\Anaconda3\envs\spurs\lib\site-packages\torch\utils\data\dataloader.py", line 187, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "f:\Anaconda3\envs\spurs\lib\site-packages\torch\utils\data\dataloader.py", line 164, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 416 and 480 in dimension 2 at c:\programdata\miniconda3\conda-bld\pytorch_1533090623466\work\aten\src\th\generic/THTensorMath.cpp:3616

**Comment by andy-yun** [comment]
@mama110 from your log, image size is mismatched. wxh = 416x480, right? did you set the width and height as mentioned? check the image width and height.

**Comment by mama110** [comment]
@andy-yun thanks for your repIy. I set the width and height as 416*416 in cfg file.

**Comment by Karthik-Suresh93** [comment]
Hi @andy-yun, I have set the image size in the cfg as 416*416. However, I still get this error in the middle of training. I am training on my own dataset, Pytorch 0.4.1. Please help me solve this issue

**Comment by andy-yun** [comment]
@Karthik-Suresh93 Will you attach or show error log or message?
