### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by sdustdk1427** [andy-yun/pytorch-0.4-yolov3#64]
i'm facing this issue when run it on my dataset File "train.py", line 149, in main
    nsamples = train(epoch)
  File "train.py", line 189, in train
    cur_model = curmodel()
  File "train.py", line 181, in curmodel
    cur_model = model.module
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in _getattr_
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'module'﻿

**Comment by sdustdk1427** [comment]
when i input "python train.py -d cfg/voc.data -c cfg/yolov3.cfg -w yolov3.weights -r"

**Comment by andy-yun** [comment]
@sdustdk1427 maybe you set the gpus in your voc.data. If you have not more than one gpus, please remove gpu ids from your voc.data.

**Comment by sdustdk1427** [comment]
thanks,but i don't have gpu ids in my voc.data,so what should i do?

**Comment by andy-yun** [comment]
Then add the following line in your voc.data
gpus=0 if you have one gpu
gpus=0,1 if you have two gpus

**Comment by sdustdk1427** [comment]
thanks,i do it,but i have a new problem:
$ python train.py -d cfg/voc.data -c cfg/yolov3.cfg -w yolov3.weights -r
Training for (1,2151)
2019-05-08 16:36:07 [001] processed 3722 samples, lr 1.000000e-03
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 157, in main
    nsamples = train(epoch)
  File "train.py", line 234, in train
    output = model(data)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/G19850028/RWJ/pytorch-0.4-yolov3-master/darknet.py", line 128, in forward
    x = self.models[ind](x)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
what should i do?thank you very much!

**Comment by sdustdk1427** [comment]
谢谢，这个问题解决了，但是我在训练完想测试mAP时遇到了新问题：
$ python scripts/my_eval.py results/comp4_det_test_ 2007_test.txt data/voc.names
Traceback (most recent call last):
  File "scripts/my_eval.py", line 12, in <module>
    from eval_ap import parse_rec
  File "/public/home/G19850028/RWJ/pytorch-0.4-yolov3-master/scripts/eval_ap.py", line 13, in <module>
    from eval_all import get_det_result_name, get_image_xml_name
  File "/public/home/G19850028/RWJ/pytorch-0.4-yolov3-master/scripts/eval_all.py", line 7, in <module>
    from darknet import Darknet
  File "./darknet.py", line 5, in <module>
    from cfg import *
  File "./cfg.py", line 2, in <module>
    from utils import convert2cpu
ImportError: cannot import name 'convert2cpu'
So what should i do ?thank you very much!

**Comment by andy-yun** [comment]
@sdustdk1427 I did same experiment on voc. But, everything is fine. Would you check the utils.py in your current directory?
In my computer, torch.__version__ is 1.0.1.
python is 3.7.3.

**Comment by sdustdk1427** [comment]
请问我的指令输的对吗？python scripts/my_eval.py results/comp4_det_test_ 2007_test.txt data/voc.names

**Comment by andy-yun** [comment]
yup .sure..
I changed small part of scripts/*.py to clarify the folder structure and uploaded them.

**Comment by sdustdk1427** [comment]
$ python scripts/my_eval.py results/comp4_det_test_ 2007_test.txt data/voc.names
Traceback (most recent call last):
  File "scripts/my_eval.py", line 11, in <module>
    from scripts.eval_ap import parse_rec
ModuleNotFoundError: No module named 'scripts'
重新下载您的scripts文件夹，但是又出现了这个错误......

**Comment by andy-yun** [comment]
@sdustdk1427  Did you perform the above command in the directory where includes utils.py and has sub directory scripts ? eval_ap.py and eval_all.py should be at the scripts folder.

**Comment by sdustdk1427** [comment]
是的，完全都是下载的您的代码。scripts文件也是下载的刚更新的。但十分感谢你能回答我的问题。

**Comment by sdustdk1427** [comment]
问题解决了，感谢你的回答~

**Comment by andy-yun** [comment]
@sdustdk1427 Next time, please use English. I can't understand Chinese.
Google translator helped me to understand your comments. ^__^
